### ISSUE TITLE
[QOL] Admin/Host view paid checklist

### ISSUE THREAD

**Issue by JohnDreemur** [shuttleday/shuttleday#29]
Requires both frontend/backend work

**Is your feature request related to a problem? Please describe.**

Not related to a problem, QOL type of request. Typically we use our own checklist to see who has paid and whatnot, would be really useful for session hosts to see who has/hasn't paid at a glance.

**Describe the solution you'd like**

Incorporate the "paid/unpaid" in the main namelist, colour coding those who haven't paid yet in default white, and those who have in green.

Once a user uploads their receipt, their ID for that session switches to "paid" state (color changes to green etc.)

**Describe alternatives you've considered**

On the receipts page, there can be 2 tabs.
TAB 1 is just a duplication of the namelist, with those who've paid in green and those who haven't in grey or something. 
TAB 2 is the receipts images we already have now just to verify payment.

**Additional context**
![Req1](https://user-images.githubusercontent.com/23275714/233304038-3bd62b5e-a723-419e-a25b-33152cc5cd0d.png)

**Comment by JohnDreemur** [comment]
This one looks cleaner, and doesn't require a separate page to be made

![image](https://user-images.githubusercontent.com/23275714/233304404-a6ef9580-2d50-4a20-99a9-27be60ab0a1c.png)

**Comment by PScoriae** [comment]
Is this something we want all users to see or just for the admins?

**Comment by JohnDreemur** [comment]
@PScoriae All users should be able to see the 'paid' state, but only hosts should be able to view receipts

**Comment by Kirixi** [comment]
@JohnDreemur do you want me to add an extra info button to them why their name is green like this?
![image](https://user-images.githubusercontent.com/70047005/233434573-d182f571-7479-4977-bde2-c4f9962abc88.png)

**Comment by JohnDreemur** [comment]
@Kirixi make it so everyone can see payment status. Not just the host and the individual user

**Comment by JohnDreemur** [comment]
I think the green is a good enough indicator that they've paid.

**Comment by JohnDreemur** [comment]
Lastly, the person who created the session should have their name as either a different color or already green'd out to indicate they're the host

**Comment by Kirixi** [comment]
@JohnDreemur have to scrap the indicator, it doesn't seem to work on mobile

**Comment by JohnDreemur** [comment]
> @JohnDreemur have to scrap the indicator, it doesn't seem to work on mobile

No worries, the implication is there ady with the green color

**Comment by Kirixi** [comment]
@JohnDreemur you mentioned putting the receipts into the same page right? There isn't enough space to put the receipts into the same tab as payment so i'm gonna make a third tab like this but it will only appear for admins
![image](https://user-images.githubusercontent.com/70047005/233652131-69925be7-d37f-4281-982e-df987fdcc84c.png)

**Comment by JohnDreemur** [comment]
The receipts being on a tab was just an alternative suggestion but if it looks good/works well then it's totally welcome. That implementation looks good
